### ISSUE TITLE
When building go-ethereum-master - fails to build

### ISSUE THREAD

**Issue by misteritguru** [ethereum/ethereum-dockers#4]
go-ethereum-master]$ docker build .
Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
Step 0 : FROM cptobvious/go-ethereum-base
 ---> 17f13d722571
Step 1 : RUN go get -v -u gopkg.in/qml.v1
 ---> Running in 4a910b02f39e
Fetching https://gopkg.in/qml.v1?go-get=1
Parsing meta tags from https://gopkg.in/qml.v1?go-get=1 (status code 200)
get "gopkg.in/qml.v1": found meta tag main.metaImport{Prefix:"gopkg.in/qml.v1", VCS:"git", RepoRoot:"https://gopkg.in/qml.v1"} at https://gopkg.in/qml.v1?go-get=1
gopkg.in/qml.v1 (download)
gopkg.in/qml.v1/cdata
gopkg.in/qml.v1/gl/glbase
gopkg.in/qml.v1
 ---> d33b89b38332
Removing intermediate container 4a910b02f39e
Step 2 : RUN go get -v -u -d github.com/ethereum/go-ethereum/ethereum
 ---> Running in 81e884959644
github.com/ethereum/go-ethereum (download)
package github.com/ethereum/go-ethereum/ethereum
        imports github.com/ethereum/go-ethereum/ethereum
        imports github.com/ethereum/go-ethereum/ethereum: cannot find package "github.com/ethereum/go-ethereum/ethereum" in any of:
        /usr/lib/go/src/pkg/github.com/ethereum/go-ethereum/ethereum (from $GOROOT)
        /root/go/src/github.com/ethereum/go-ethereum/ethereum (from $GOPATH)
INFO[0040] The command [/bin/sh -c go get -v -u -d github.com/ethereum/go-ethereum/ethereum] returned a non-zero code: 1

**Comment by misteritguru** [comment]
I think I 'fixed' this issue by updating the docker file to pull from the correct URL - at least one that I think it should be 

RUN go get -v -u -d github.com/ethereum/go-ethereum/cmd/ethereum
RUN go get -v -u -d github.com/ethereum/go-ethereum/cmd/mist

Once I can get it building fully, I'll submit a pull request

**Comment by caktux** [comment]
Only the *-base and *-buildslave* Dockerfiles are being used, others have only been kept for possible future use with the testing system. You should use the one in the go-ethereum repo directly.
